language: julia

os: 
  - osx
  - linux

julia: 
  - 1

notifications:
  email: true

install: travis_wait 20 julia --project -e 'using Pkg; Pkg.instantiate()'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("NPSMC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
